<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* @app/vendor/symfony/flex/src/Command/DumpEnvCommand.php */
class __TwigTemplate_158a7571ce2cdf74c0ec08e373f92a82924580b5d91ab68b63ffd4c380814e0f extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "@app/vendor/symfony/flex/src/Command/DumpEnvCommand.php"));

        // line 1
        echo "<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\\Flex\\Command;

use Composer\\Command\\BaseCommand;
use Composer\\Config;
use Symfony\\Component\\Console\\Input\\InputArgument;
use Symfony\\Component\\Console\\Input\\InputInterface;
use Symfony\\Component\\Console\\Input\\InputOption;
use Symfony\\Component\\Console\\Output\\OutputInterface;
use Symfony\\Component\\Dotenv\\Dotenv;
use Symfony\\Flex\\Options;

class DumpEnvCommand extends BaseCommand
{
    private \$config;
    private \$options;

    public function __construct(Config \$config, Options \$options)
    {
        \$this->config = \$config;
        \$this->options = \$options;

        parent::__construct();
    }

    protected function configure()
    {
        \$this->setName('symfony:dump-env')
            ->setAliases(['dump-env'])
            ->setDescription('Compiles .env files to .env.local.php.')
            ->setDefinition([
                new InputArgument('env', InputArgument::REQUIRED, 'The application environment to dump .env files for - e.g. \"prod\".'),
            ])
            ->addOption('empty', null, InputOption::VALUE_NONE, 'Ignore the content of .env files')
        ;
    }

    protected function execute(InputInterface \$input, OutputInterface \$output): int
    {
        \$_SERVER['APP_ENV'] = \$env = \$input->getArgument('env');
        \$path = \$this->options->get('root-dir').'/.env';

        \$vars = \$input->getOption('empty') ? ['APP_ENV' => \$env] : \$this->loadEnv(\$path, \$env);
        \$vars = var_export(\$vars, true);
        \$vars = <<<EOF
<?php

// This file was generated by running \"composer dump-env \$env\"

return \$vars;

EOF;
        file_put_contents(\$path.'.local.php', \$vars, LOCK_EX);

        \$this->getIO()->writeError('Successfully dumped .env files in <info>.env.local.php</>');

        return 0;
    }

    private function loadEnv(string \$path, string \$env): array
    {
        if (!file_exists(\$autoloadFile = \$this->config->get('vendor-dir').'/autoload.php')) {
            throw new \\RuntimeException(sprintf('Please run \"composer install\" before running this command: \"%s\" not found.', \$autoloadFile));
        }

        if (!class_exists(Dotenv::class)) {
            throw new \\RuntimeException('Please run \"composer require symfony/dotenv\" to load the \".env\" files configuring the application.');
        }

        \$globalsBackup = [\$_SERVER, \$_ENV];
        unset(\$_SERVER['APP_ENV']);
        \$_ENV = ['APP_ENV' => \$env];
        \$_SERVER['SYMFONY_DOTENV_VARS'] = implode(',', array_keys(\$_SERVER));
        putenv('SYMFONY_DOTENV_VARS='.\$_SERVER['SYMFONY_DOTENV_VARS']);

        try {
            if (method_exists(Dotenv::class, 'usePutenv')) {
                \$dotenv = new Dotenv();
            } else {
                \$dotenv = new Dotenv(false);
            }

            if (method_exists(\$dotenv, 'loadEnv')) {
                \$dotenv->loadEnv(\$path);
            } else {
                // fallback code in case your Dotenv component is not 4.2 or higher (when loadEnv() was added)
                \$dotenv->load(file_exists(\$path) || !file_exists(\$p = \"\$path.dist\") ? \$path : \$p);

                if ('test' !== \$env && file_exists(\$p = \"\$path.local\")) {
                    \$dotenv->load(\$p);
                }

                if (file_exists(\$p = \"\$path.\$env\")) {
                    \$dotenv->load(\$p);
                }

                if (file_exists(\$p = \"\$path.\$env.local\")) {
                    \$dotenv->load(\$p);
                }
            }

            unset(\$_ENV['SYMFONY_DOTENV_VARS']);
            \$env = \$_ENV;
        } finally {
            list(\$_SERVER, \$_ENV) = \$globalsBackup;
        }

        return \$env;
    }
}
";
        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "@app/vendor/symfony/flex/src/Command/DumpEnvCommand.php";
    }

    public function getDebugInfo()
    {
        return array (  40 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\\Flex\\Command;

use Composer\\Command\\BaseCommand;
use Composer\\Config;
use Symfony\\Component\\Console\\Input\\InputArgument;
use Symfony\\Component\\Console\\Input\\InputInterface;
use Symfony\\Component\\Console\\Input\\InputOption;
use Symfony\\Component\\Console\\Output\\OutputInterface;
use Symfony\\Component\\Dotenv\\Dotenv;
use Symfony\\Flex\\Options;

class DumpEnvCommand extends BaseCommand
{
    private \$config;
    private \$options;

    public function __construct(Config \$config, Options \$options)
    {
        \$this->config = \$config;
        \$this->options = \$options;

        parent::__construct();
    }

    protected function configure()
    {
        \$this->setName('symfony:dump-env')
            ->setAliases(['dump-env'])
            ->setDescription('Compiles .env files to .env.local.php.')
            ->setDefinition([
                new InputArgument('env', InputArgument::REQUIRED, 'The application environment to dump .env files for - e.g. \"prod\".'),
            ])
            ->addOption('empty', null, InputOption::VALUE_NONE, 'Ignore the content of .env files')
        ;
    }

    protected function execute(InputInterface \$input, OutputInterface \$output): int
    {
        \$_SERVER['APP_ENV'] = \$env = \$input->getArgument('env');
        \$path = \$this->options->get('root-dir').'/.env';

        \$vars = \$input->getOption('empty') ? ['APP_ENV' => \$env] : \$this->loadEnv(\$path, \$env);
        \$vars = var_export(\$vars, true);
        \$vars = <<<EOF
<?php

// This file was generated by running \"composer dump-env \$env\"

return \$vars;

EOF;
        file_put_contents(\$path.'.local.php', \$vars, LOCK_EX);

        \$this->getIO()->writeError('Successfully dumped .env files in <info>.env.local.php</>');

        return 0;
    }

    private function loadEnv(string \$path, string \$env): array
    {
        if (!file_exists(\$autoloadFile = \$this->config->get('vendor-dir').'/autoload.php')) {
            throw new \\RuntimeException(sprintf('Please run \"composer install\" before running this command: \"%s\" not found.', \$autoloadFile));
        }

        if (!class_exists(Dotenv::class)) {
            throw new \\RuntimeException('Please run \"composer require symfony/dotenv\" to load the \".env\" files configuring the application.');
        }

        \$globalsBackup = [\$_SERVER, \$_ENV];
        unset(\$_SERVER['APP_ENV']);
        \$_ENV = ['APP_ENV' => \$env];
        \$_SERVER['SYMFONY_DOTENV_VARS'] = implode(',', array_keys(\$_SERVER));
        putenv('SYMFONY_DOTENV_VARS='.\$_SERVER['SYMFONY_DOTENV_VARS']);

        try {
            if (method_exists(Dotenv::class, 'usePutenv')) {
                \$dotenv = new Dotenv();
            } else {
                \$dotenv = new Dotenv(false);
            }

            if (method_exists(\$dotenv, 'loadEnv')) {
                \$dotenv->loadEnv(\$path);
            } else {
                // fallback code in case your Dotenv component is not 4.2 or higher (when loadEnv() was added)
                \$dotenv->load(file_exists(\$path) || !file_exists(\$p = \"\$path.dist\") ? \$path : \$p);

                if ('test' !== \$env && file_exists(\$p = \"\$path.local\")) {
                    \$dotenv->load(\$p);
                }

                if (file_exists(\$p = \"\$path.\$env\")) {
                    \$dotenv->load(\$p);
                }

                if (file_exists(\$p = \"\$path.\$env.local\")) {
                    \$dotenv->load(\$p);
                }
            }

            unset(\$_ENV['SYMFONY_DOTENV_VARS']);
            \$env = \$_ENV;
        } finally {
            list(\$_SERVER, \$_ENV) = \$globalsBackup;
        }

        return \$env;
    }
}
", "@app/vendor/symfony/flex/src/Command/DumpEnvCommand.php", "C:\\wamp64\\www\\QuillBlog\\vendor\\symfony\\flex\\src\\Command\\DumpEnvCommand.php");
    }
}
