<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* @app/vendor/composer/autoload_psr4.php */
class __TwigTemplate_34e52da19763b90f4e22540c366d19e0c31d27f761c3e3af43c95a58e0d72f24 extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "@app/vendor/composer/autoload_psr4.php"));

        // line 1
        echo "<?php

// autoload_psr4.php @generated by Composer

\$vendorDir = dirname(dirname(__FILE__));
\$baseDir = dirname(\$vendorDir);

return array(
    'Zend\\\\EventManager\\\\' => array(\$vendorDir . '/zendframework/zend-eventmanager/src'),
    'Zend\\\\Code\\\\' => array(\$vendorDir . '/zendframework/zend-code/src'),
    'Twig\\\\Extra\\\\TwigExtraBundle\\\\' => array(\$vendorDir . '/twig/extra-bundle/src'),
    'Twig\\\\' => array(\$vendorDir . '/twig/twig/src'),
    'Symfony\\\\Polyfill\\\\Php73\\\\' => array(\$vendorDir . '/symfony/polyfill-php73'),
    'Symfony\\\\Polyfill\\\\Mbstring\\\\' => array(\$vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\\\Polyfill\\\\Intl\\\\Idn\\\\' => array(\$vendorDir . '/symfony/polyfill-intl-idn'),
    'Symfony\\\\Flex\\\\' => array(\$vendorDir . '/symfony/flex/src'),
    'Symfony\\\\Contracts\\\\Translation\\\\' => array(\$vendorDir . '/symfony/translation-contracts'),
    'Symfony\\\\Contracts\\\\Service\\\\' => array(\$vendorDir . '/symfony/service-contracts'),
    'Symfony\\\\Contracts\\\\EventDispatcher\\\\' => array(\$vendorDir . '/symfony/event-dispatcher-contracts'),
    'Symfony\\\\Contracts\\\\Cache\\\\' => array(\$vendorDir . '/symfony/cache-contracts'),
    'Symfony\\\\Component\\\\Yaml\\\\' => array(\$vendorDir . '/symfony/yaml'),
    'Symfony\\\\Component\\\\VarExporter\\\\' => array(\$vendorDir . '/symfony/var-exporter'),
    'Symfony\\\\Component\\\\VarDumper\\\\' => array(\$vendorDir . '/symfony/var-dumper'),
    'Symfony\\\\Component\\\\Stopwatch\\\\' => array(\$vendorDir . '/symfony/stopwatch'),
    'Symfony\\\\Component\\\\Routing\\\\' => array(\$vendorDir . '/symfony/routing'),
    'Symfony\\\\Component\\\\Mime\\\\' => array(\$vendorDir . '/symfony/mime'),
    'Symfony\\\\Component\\\\HttpKernel\\\\' => array(\$vendorDir . '/symfony/http-kernel'),
    'Symfony\\\\Component\\\\HttpFoundation\\\\' => array(\$vendorDir . '/symfony/http-foundation'),
    'Symfony\\\\Component\\\\Finder\\\\' => array(\$vendorDir . '/symfony/finder'),
    'Symfony\\\\Component\\\\Filesystem\\\\' => array(\$vendorDir . '/symfony/filesystem'),
    'Symfony\\\\Component\\\\EventDispatcher\\\\' => array(\$vendorDir . '/symfony/event-dispatcher'),
    'Symfony\\\\Component\\\\ErrorHandler\\\\' => array(\$vendorDir . '/symfony/error-handler'),
    'Symfony\\\\Component\\\\Dotenv\\\\' => array(\$vendorDir . '/symfony/dotenv'),
    'Symfony\\\\Component\\\\DependencyInjection\\\\' => array(\$vendorDir . '/symfony/dependency-injection'),
    'Symfony\\\\Component\\\\Console\\\\' => array(\$vendorDir . '/symfony/console'),
    'Symfony\\\\Component\\\\Config\\\\' => array(\$vendorDir . '/symfony/config'),
    'Symfony\\\\Component\\\\Cache\\\\' => array(\$vendorDir . '/symfony/cache'),
    'Symfony\\\\Component\\\\Asset\\\\' => array(\$vendorDir . '/symfony/asset'),
    'Symfony\\\\Bundle\\\\TwigBundle\\\\' => array(\$vendorDir . '/symfony/twig-bundle'),
    'Symfony\\\\Bundle\\\\MakerBundle\\\\' => array(\$vendorDir . '/symfony/maker-bundle/src'),
    'Symfony\\\\Bundle\\\\FrameworkBundle\\\\' => array(\$vendorDir . '/symfony/framework-bundle'),
    'Symfony\\\\Bridge\\\\Twig\\\\' => array(\$vendorDir . '/symfony/twig-bridge'),
    'Symfony\\\\Bridge\\\\Doctrine\\\\' => array(\$vendorDir . '/symfony/doctrine-bridge'),
    'Psr\\\\Log\\\\' => array(\$vendorDir . '/psr/log/Psr/Log'),
    'Psr\\\\EventDispatcher\\\\' => array(\$vendorDir . '/psr/event-dispatcher/src'),
    'Psr\\\\Container\\\\' => array(\$vendorDir . '/psr/container/src'),
    'Psr\\\\Cache\\\\' => array(\$vendorDir . '/psr/cache/src'),
    'PhpParser\\\\' => array(\$vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'PackageVersions\\\\' => array(\$vendorDir . '/ocramius/package-versions/src/PackageVersions'),
    'Doctrine\\\\Persistence\\\\' => array(\$vendorDir . '/doctrine/persistence/lib/Doctrine/Persistence'),
    'Doctrine\\\\ORM\\\\' => array(\$vendorDir . '/doctrine/orm/lib/Doctrine/ORM'),
    'Doctrine\\\\Migrations\\\\' => array(\$vendorDir . '/doctrine/migrations/lib/Doctrine/Migrations'),
    'Doctrine\\\\Instantiator\\\\' => array(\$vendorDir . '/doctrine/instantiator/src/Doctrine/Instantiator'),
    'Doctrine\\\\DBAL\\\\' => array(\$vendorDir . '/doctrine/dbal/lib/Doctrine/DBAL'),
    'Doctrine\\\\Common\\\\Lexer\\\\' => array(\$vendorDir . '/doctrine/lexer/lib/Doctrine/Common/Lexer'),
    'Doctrine\\\\Common\\\\Inflector\\\\' => array(\$vendorDir . '/doctrine/inflector/lib/Doctrine/Common/Inflector'),
    'Doctrine\\\\Common\\\\Collections\\\\' => array(\$vendorDir . '/doctrine/collections/lib/Doctrine/Common/Collections'),
    'Doctrine\\\\Common\\\\Cache\\\\' => array(\$vendorDir . '/doctrine/cache/lib/Doctrine/Common/Cache'),
    'Doctrine\\\\Common\\\\Annotations\\\\' => array(\$vendorDir . '/doctrine/annotations/lib/Doctrine/Common/Annotations'),
    'Doctrine\\\\Common\\\\' => array(\$vendorDir . '/doctrine/common/lib/Doctrine/Common', \$vendorDir . '/doctrine/event-manager/lib/Doctrine/Common', \$vendorDir . '/doctrine/persistence/lib/Doctrine/Common', \$vendorDir . '/doctrine/reflection/lib/Doctrine/Common'),
    'Doctrine\\\\Bundle\\\\MigrationsBundle\\\\' => array(\$vendorDir . '/doctrine/doctrine-migrations-bundle'),
    'Doctrine\\\\Bundle\\\\DoctrineBundle\\\\' => array(\$vendorDir . '/doctrine/doctrine-bundle'),
    'App\\\\Tests\\\\' => array(\$baseDir . '/tests'),
    'App\\\\' => array(\$baseDir . '/src'),
);
";
        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "@app/vendor/composer/autoload_psr4.php";
    }

    public function getDebugInfo()
    {
        return array (  40 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

// autoload_psr4.php @generated by Composer

\$vendorDir = dirname(dirname(__FILE__));
\$baseDir = dirname(\$vendorDir);

return array(
    'Zend\\\\EventManager\\\\' => array(\$vendorDir . '/zendframework/zend-eventmanager/src'),
    'Zend\\\\Code\\\\' => array(\$vendorDir . '/zendframework/zend-code/src'),
    'Twig\\\\Extra\\\\TwigExtraBundle\\\\' => array(\$vendorDir . '/twig/extra-bundle/src'),
    'Twig\\\\' => array(\$vendorDir . '/twig/twig/src'),
    'Symfony\\\\Polyfill\\\\Php73\\\\' => array(\$vendorDir . '/symfony/polyfill-php73'),
    'Symfony\\\\Polyfill\\\\Mbstring\\\\' => array(\$vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\\\Polyfill\\\\Intl\\\\Idn\\\\' => array(\$vendorDir . '/symfony/polyfill-intl-idn'),
    'Symfony\\\\Flex\\\\' => array(\$vendorDir . '/symfony/flex/src'),
    'Symfony\\\\Contracts\\\\Translation\\\\' => array(\$vendorDir . '/symfony/translation-contracts'),
    'Symfony\\\\Contracts\\\\Service\\\\' => array(\$vendorDir . '/symfony/service-contracts'),
    'Symfony\\\\Contracts\\\\EventDispatcher\\\\' => array(\$vendorDir . '/symfony/event-dispatcher-contracts'),
    'Symfony\\\\Contracts\\\\Cache\\\\' => array(\$vendorDir . '/symfony/cache-contracts'),
    'Symfony\\\\Component\\\\Yaml\\\\' => array(\$vendorDir . '/symfony/yaml'),
    'Symfony\\\\Component\\\\VarExporter\\\\' => array(\$vendorDir . '/symfony/var-exporter'),
    'Symfony\\\\Component\\\\VarDumper\\\\' => array(\$vendorDir . '/symfony/var-dumper'),
    'Symfony\\\\Component\\\\Stopwatch\\\\' => array(\$vendorDir . '/symfony/stopwatch'),
    'Symfony\\\\Component\\\\Routing\\\\' => array(\$vendorDir . '/symfony/routing'),
    'Symfony\\\\Component\\\\Mime\\\\' => array(\$vendorDir . '/symfony/mime'),
    'Symfony\\\\Component\\\\HttpKernel\\\\' => array(\$vendorDir . '/symfony/http-kernel'),
    'Symfony\\\\Component\\\\HttpFoundation\\\\' => array(\$vendorDir . '/symfony/http-foundation'),
    'Symfony\\\\Component\\\\Finder\\\\' => array(\$vendorDir . '/symfony/finder'),
    'Symfony\\\\Component\\\\Filesystem\\\\' => array(\$vendorDir . '/symfony/filesystem'),
    'Symfony\\\\Component\\\\EventDispatcher\\\\' => array(\$vendorDir . '/symfony/event-dispatcher'),
    'Symfony\\\\Component\\\\ErrorHandler\\\\' => array(\$vendorDir . '/symfony/error-handler'),
    'Symfony\\\\Component\\\\Dotenv\\\\' => array(\$vendorDir . '/symfony/dotenv'),
    'Symfony\\\\Component\\\\DependencyInjection\\\\' => array(\$vendorDir . '/symfony/dependency-injection'),
    'Symfony\\\\Component\\\\Console\\\\' => array(\$vendorDir . '/symfony/console'),
    'Symfony\\\\Component\\\\Config\\\\' => array(\$vendorDir . '/symfony/config'),
    'Symfony\\\\Component\\\\Cache\\\\' => array(\$vendorDir . '/symfony/cache'),
    'Symfony\\\\Component\\\\Asset\\\\' => array(\$vendorDir . '/symfony/asset'),
    'Symfony\\\\Bundle\\\\TwigBundle\\\\' => array(\$vendorDir . '/symfony/twig-bundle'),
    'Symfony\\\\Bundle\\\\MakerBundle\\\\' => array(\$vendorDir . '/symfony/maker-bundle/src'),
    'Symfony\\\\Bundle\\\\FrameworkBundle\\\\' => array(\$vendorDir . '/symfony/framework-bundle'),
    'Symfony\\\\Bridge\\\\Twig\\\\' => array(\$vendorDir . '/symfony/twig-bridge'),
    'Symfony\\\\Bridge\\\\Doctrine\\\\' => array(\$vendorDir . '/symfony/doctrine-bridge'),
    'Psr\\\\Log\\\\' => array(\$vendorDir . '/psr/log/Psr/Log'),
    'Psr\\\\EventDispatcher\\\\' => array(\$vendorDir . '/psr/event-dispatcher/src'),
    'Psr\\\\Container\\\\' => array(\$vendorDir . '/psr/container/src'),
    'Psr\\\\Cache\\\\' => array(\$vendorDir . '/psr/cache/src'),
    'PhpParser\\\\' => array(\$vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'PackageVersions\\\\' => array(\$vendorDir . '/ocramius/package-versions/src/PackageVersions'),
    'Doctrine\\\\Persistence\\\\' => array(\$vendorDir . '/doctrine/persistence/lib/Doctrine/Persistence'),
    'Doctrine\\\\ORM\\\\' => array(\$vendorDir . '/doctrine/orm/lib/Doctrine/ORM'),
    'Doctrine\\\\Migrations\\\\' => array(\$vendorDir . '/doctrine/migrations/lib/Doctrine/Migrations'),
    'Doctrine\\\\Instantiator\\\\' => array(\$vendorDir . '/doctrine/instantiator/src/Doctrine/Instantiator'),
    'Doctrine\\\\DBAL\\\\' => array(\$vendorDir . '/doctrine/dbal/lib/Doctrine/DBAL'),
    'Doctrine\\\\Common\\\\Lexer\\\\' => array(\$vendorDir . '/doctrine/lexer/lib/Doctrine/Common/Lexer'),
    'Doctrine\\\\Common\\\\Inflector\\\\' => array(\$vendorDir . '/doctrine/inflector/lib/Doctrine/Common/Inflector'),
    'Doctrine\\\\Common\\\\Collections\\\\' => array(\$vendorDir . '/doctrine/collections/lib/Doctrine/Common/Collections'),
    'Doctrine\\\\Common\\\\Cache\\\\' => array(\$vendorDir . '/doctrine/cache/lib/Doctrine/Common/Cache'),
    'Doctrine\\\\Common\\\\Annotations\\\\' => array(\$vendorDir . '/doctrine/annotations/lib/Doctrine/Common/Annotations'),
    'Doctrine\\\\Common\\\\' => array(\$vendorDir . '/doctrine/common/lib/Doctrine/Common', \$vendorDir . '/doctrine/event-manager/lib/Doctrine/Common', \$vendorDir . '/doctrine/persistence/lib/Doctrine/Common', \$vendorDir . '/doctrine/reflection/lib/Doctrine/Common'),
    'Doctrine\\\\Bundle\\\\MigrationsBundle\\\\' => array(\$vendorDir . '/doctrine/doctrine-migrations-bundle'),
    'Doctrine\\\\Bundle\\\\DoctrineBundle\\\\' => array(\$vendorDir . '/doctrine/doctrine-bundle'),
    'App\\\\Tests\\\\' => array(\$baseDir . '/tests'),
    'App\\\\' => array(\$baseDir . '/src'),
);
", "@app/vendor/composer/autoload_psr4.php", "C:\\wamp64\\www\\QuillBlog\\vendor\\composer\\autoload_psr4.php");
    }
}
