<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* @app/var/cache/dev/url_generating_routes.php */
class __TwigTemplate_8a8a6688a3d09323808d9a64268b797da9dbd5beded1442ee5f8b0f32406533f extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "@app/var/cache/dev/url_generating_routes.php"));

        // line 1
        echo "<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\\\d+', 'code', true], ['text', '/_error']], [], []],
    'blog' => [[], ['_controller' => 'App\\\\Controller\\\\BlogController::index'], [], [['text', '/']], [], []],
];
";
        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "@app/var/cache/dev/url_generating_routes.php";
    }

    public function getDebugInfo()
    {
        return array (  40 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\\\d+', 'code', true], ['text', '/_error']], [], []],
    'blog' => [[], ['_controller' => 'App\\\\Controller\\\\BlogController::index'], [], [['text', '/']], [], []],
];
", "@app/var/cache/dev/url_generating_routes.php", "C:\\wamp64\\www\\QuillBlog\\var\\cache\\dev\\url_generating_routes.php");
    }
}
