<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* @app/var/cache/dev/App_KernelDevDebugContainer.php */
class __TwigTemplate_7b5c496283240eeea61e0b6fa0410d52008ae5ef4a4879d38bbcc7934ad026a1 extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "@app/var/cache/dev/App_KernelDevDebugContainer.php"));

        // line 1
        echo "<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\\class_exists(\\ContainerVScOxgY\\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVScOxgY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVScOxgY.legacy');

    return;
}

if (!\\class_exists(App_KernelDevDebugContainer::class, false)) {
    \\class_alias(\\ContainerVScOxgY\\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \\ContainerVScOxgY\\App_KernelDevDebugContainer([
    'container.build_hash' => 'VScOxgY',
    'container.build_id' => 'a27f526f',
    'container.build_time' => 1584022473,
], __DIR__.\\DIRECTORY_SEPARATOR.'ContainerVScOxgY');
";
        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "@app/var/cache/dev/App_KernelDevDebugContainer.php";
    }

    public function getDebugInfo()
    {
        return array (  40 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\\class_exists(\\ContainerVScOxgY\\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVScOxgY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVScOxgY.legacy');

    return;
}

if (!\\class_exists(App_KernelDevDebugContainer::class, false)) {
    \\class_alias(\\ContainerVScOxgY\\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \\ContainerVScOxgY\\App_KernelDevDebugContainer([
    'container.build_hash' => 'VScOxgY',
    'container.build_id' => 'a27f526f',
    'container.build_time' => 1584022473,
], __DIR__.\\DIRECTORY_SEPARATOR.'ContainerVScOxgY');
", "@app/var/cache/dev/App_KernelDevDebugContainer.php", "C:\\wamp64\\www\\QuillBlog\\var\\cache\\dev\\App_KernelDevDebugContainer.php");
    }
}
