<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* @app/vendor/symfony/routing/Generator/Dumper/CompiledUrlGeneratorDumper.php */
class __TwigTemplate_7c82069aa1a20b930856da10bc181062fd6ed13813cd116a3ff8df3300deb30b extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "@app/vendor/symfony/routing/Generator/Dumper/CompiledUrlGeneratorDumper.php"));

        // line 1
        echo "<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\\Component\\Routing\\Generator\\Dumper;

use Symfony\\Component\\Routing\\Matcher\\Dumper\\CompiledUrlMatcherDumper;

/**
 * CompiledUrlGeneratorDumper creates a PHP array to be used with CompiledUrlGenerator.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 * @author Tobias Schultze <http://tobion.de>
 * @author Nicolas Grekas <p@tchwork.com>
 */
class CompiledUrlGeneratorDumper extends GeneratorDumper
{
    public function getCompiledRoutes(): array
    {
        \$compiledRoutes = [];
        foreach (\$this->getRoutes()->all() as \$name => \$route) {
            \$compiledRoute = \$route->compile();

            \$compiledRoutes[\$name] = [
                \$compiledRoute->getVariables(),
                \$route->getDefaults(),
                \$route->getRequirements(),
                \$compiledRoute->getTokens(),
                \$compiledRoute->getHostTokens(),
                \$route->getSchemes(),
            ];
        }

        return \$compiledRoutes;
    }

    /**
     * {@inheritdoc}
     */
    public function dump(array \$options = [])
    {
        return <<<EOF
<?php

// This file has been auto-generated by the Symfony Routing Component.

return [{\$this->generateDeclaredRoutes()}
];

EOF;
    }

    /**
     * Generates PHP code representing an array of defined routes
     * together with the routes properties (e.g. requirements).
     */
    private function generateDeclaredRoutes(): string
    {
        \$routes = '';
        foreach (\$this->getCompiledRoutes() as \$name => \$properties) {
            \$routes .= sprintf(\"\\n    '%s' => %s,\", \$name, CompiledUrlMatcherDumper::export(\$properties));
        }

        return \$routes;
    }
}
";
        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "@app/vendor/symfony/routing/Generator/Dumper/CompiledUrlGeneratorDumper.php";
    }

    public function getDebugInfo()
    {
        return array (  40 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\\Component\\Routing\\Generator\\Dumper;

use Symfony\\Component\\Routing\\Matcher\\Dumper\\CompiledUrlMatcherDumper;

/**
 * CompiledUrlGeneratorDumper creates a PHP array to be used with CompiledUrlGenerator.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 * @author Tobias Schultze <http://tobion.de>
 * @author Nicolas Grekas <p@tchwork.com>
 */
class CompiledUrlGeneratorDumper extends GeneratorDumper
{
    public function getCompiledRoutes(): array
    {
        \$compiledRoutes = [];
        foreach (\$this->getRoutes()->all() as \$name => \$route) {
            \$compiledRoute = \$route->compile();

            \$compiledRoutes[\$name] = [
                \$compiledRoute->getVariables(),
                \$route->getDefaults(),
                \$route->getRequirements(),
                \$compiledRoute->getTokens(),
                \$compiledRoute->getHostTokens(),
                \$route->getSchemes(),
            ];
        }

        return \$compiledRoutes;
    }

    /**
     * {@inheritdoc}
     */
    public function dump(array \$options = [])
    {
        return <<<EOF
<?php

// This file has been auto-generated by the Symfony Routing Component.

return [{\$this->generateDeclaredRoutes()}
];

EOF;
    }

    /**
     * Generates PHP code representing an array of defined routes
     * together with the routes properties (e.g. requirements).
     */
    private function generateDeclaredRoutes(): string
    {
        \$routes = '';
        foreach (\$this->getCompiledRoutes() as \$name => \$properties) {
            \$routes .= sprintf(\"\\n    '%s' => %s,\", \$name, CompiledUrlMatcherDumper::export(\$properties));
        }

        return \$routes;
    }
}
", "@app/vendor/symfony/routing/Generator/Dumper/CompiledUrlGeneratorDumper.php", "C:\\wamp64\\www\\QuillBlog\\vendor\\symfony\\routing\\Generator\\Dumper\\CompiledUrlGeneratorDumper.php");
    }
}
