<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'blog' => [[], ['_controller' => 'App\\Controller\\BlogController::index'], [], [['text', '/']], [], []],
    'blogartikel' => [['id'], ['id' => null, '_controller' => 'App\\Controller\\BlogController::blogartikel'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/blogartikel']], [], []],
    'blogartikel_ajax' => [[], ['_controller' => 'App\\Controller\\BlogController::store'], [], [['text', '/blog/ajax']], [], []],
];
